### ISSUE TITLE
Stack Error when trying to start SnapPass

### ISSUE THREAD

**Issue by azaloum90** [pinterest/snappass#134]
Getting this massive stack error when I run "snappass" after installing:

`C:\Users\avzaloum>snappass
Traceback (most recent call last):
  File "c:\program files\python39\lib\site-packages\redis\connection.py", line 559, in connect
    sock = self._connect()
  File "c:\program files\python39\lib\site-packages\redis\connection.py", line 615, in _connect
    raise err
  File "c:\program files\python39\lib\site-packages\redis\connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python39\lib\site-packages\snappass\main.py", line 48, in inner
    redis_client.ping()
  File "c:\program files\python39\lib\site-packages\redis\client.py", line 1378, in ping
    return self.execute_command('PING')
  File "c:\program files\python39\lib\site-packages\redis\client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "c:\program files\python39\lib\site-packages\redis\connection.py", line 1192, in get_connection
    connection.connect()
  File "c:\program files\python39\lib\site-packages\redis\connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python39\Scripts\snappass.exe\__main__.py", line 7, in <module>
  File "c:\program files\python39\lib\site-packages\snappass\main.py", line 51, in inner
    print('Failed to connect to redis! %s' % e.message)
AttributeError: 'ConnectionError' object has no attribute 'message' `

I tried uninstalling snappass, then running "pip install redis", then running "pip install snappass" again.  Still the same thing.  Checked the Readme, shows absolutely no other fixes for this.  Please advise!

Thanks,
Adam

**Comment by jparise** [comment]
The root issue is the inability to connect to a Redis instance on `localhost:6379`:

> redis.exceptions.ConnectionError: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.

Do you have [Redis](https://redis.io/) itself (in addition to the `redis` Python package) installed and running?

**Comment by azaloum90** [comment]
Apparently, I did not have Redis installed.... Wish there was some clarification on that in the readme.  Working properly now.  Thanks!

**Comment by jparise** [comment]
I added a note to the readme in a94e16802dc5f7475c8e9bab2e2db89dc2a0dbd8.
