### ISSUE TITLE
Catch Connection Error when redis isn't up

### ISSUE THREAD

**Issue by nichochar** [pinterest/snappass#22]
If redis-server isn't running, we don't catch the connection error (see tracktrace below), and display a Flask error page. 
We should catch it cleanly ad display an error page.
```
Traceback (most recent call last):
  File "/Users/nicholas/dev/snappass/env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/nicholas/dev/snappass/env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/nicholas/dev/snappass/env/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/nicholas/dev/snappass/env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/nicholas/dev/snappass/env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/nicholas/dev/snappass/env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/nicholas/dev/snappass/env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/nicholas/dev/snappass/env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/nicholas/dev/snappass/snappass/main.py", line 66, in handle_password
    key = set_password(password, ttl)
  File "/Users/nicholas/dev/snappass/snappass/main.py", line 27, in set_password
    redis_client.set(key, password)
  File "/Users/nicholas/dev/snappass/env/lib/python2.7/site-packages/redis/client.py", line 808, in set
    return self.execute_command('SET', *pieces)
  File "/Users/nicholas/dev/snappass/env/lib/python2.7/site-packages/redis/client.py", line 397, in execute_command
    connection.send_command(*args)
  File "/Users/nicholas/dev/snappass/env/lib/python2.7/site-packages/redis/connection.py", line 306, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/Users/nicholas/dev/snappass/env/lib/python2.7/site-packages/redis/connection.py", line 288, in send_packed_command
    self.connect()
  File "/Users/nicholas/dev/snappass/env/lib/python2.7/site-packages/redis/connection.py", line 235, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 61 connecting localhost:6379. Connection refused.
```

**Comment by nichochar** [comment]
Fixed in https://github.com/pinterest/snappass/pull/24
