### ISSUE TITLE
Incorrect handling of connection errors

### ISSUE THREAD

**Issue by samueldg** [pinterest/snappass#40]
Looks like connection error handler code throws an exception (at least in this version of the Redis client):

```
Traceback (most recent call last):
  File ".../snappass/venv/bin/snappass", line 9, in <module>
    load_entry_point('snappass', 'console_scripts', 'snappass')()
  File ".../snappass/snappass/main.py", line 40, in inner
    print('Failed to connect to redis! %s' % e.message)
AttributeError: 'ConnectionError' object has no attribute 'message'
```

And double-checking:

```python
>>> from redis.exceptions import ConnectionError
>>> 'message' in dir(ConnectionError)
False
```

Using `str(e)` probably solves the issue, and I guess adding a test would make sense.

Relates to the changes in https://github.com/pinterest/snappass/pull/24

**Comment by Coder-aadarsh** [comment]
It seems error indicates that an AttributeError is raised because the 'ConnectionError' object has no 'message' attribute. So I think using str(e) instead of e.message is reasonable, as str(e) will convert the exception object to a string and include the error message.
