### ISSUE TITLE
Error 61 connecting to localhost:6379

### ISSUE THREAD

**Issue by dhniels** [pinterest/snappass#54]
redis.exceptions.ConnectionError
ConnectionError: Error 61 connecting to localhost:6379. Connection refused.

Traceback (most recent call last)
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1994, in __call__
return self.wsgi_app(environ, start_response)
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
response = self.handle_exception(e)
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/usr/local/lib/python2.7/site-packages/snappass/main.py", line 65, in handle_password
key = set_password(password, ttl)
File "/usr/local/lib/python2.7/site-packages/snappass/main.py", line 28, in set_password
redis_client.set(key, password)
File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 1072, in set
return self.execute_command('SET', *pieces)
File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 578, in execute_command
connection.send_command(*args)
File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 563, in send_command
self.send_packed_command(self.pack_command(*args))
File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 538, in send_packed_command
self.connect()
File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 442, in connect
Open an interactive python shell in this frameraise ConnectionError(self._error_message(e))
ConnectionError: Error 61 connecting to localhost:6379. Connection refused.

**Comment by dhniels** [comment]
Figured out. Wasn't running an active redis server. Might want to just delete or mark this solved.

**Comment by dhniels** [comment]
Wasn't running redis prior to running snappass. Whoops! Mark solved.
