### ISSUE TITLE
install fails on RHEL 6.8 / python 2.6

### ISSUE THREAD

**Issue by jschauma** [pinterest/snappass#74]
On RHEL6.8, installation via 'sudo pip install snappass' fails:

```
Installing collected packages: idna, asn1crypto, enum34, ipaddress, cryptography, click, itsdangerou
s, Werkzeug, MarkupSafe, Jinja2, Flask, redis, snappass
  Running setup.py install for cryptography
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-
build-_ihHnN/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().re
place('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-lm4tPa-record/install-record.txt 
--single-version-externally-managed --compile:
    Couldn't find index page for 'cffi' (maybe misspelled?)
    No local packages or download links found for cffi>=1.7
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-_ihHnN/cryptography/setup.py", line 307, in <module>
        **keywords_with_side_effects(sys.argv)
      File "/usr/lib64/python2.6/distutils/core.py", line 113, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.6/site-packages/setuptools/dist.py", line 221, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/usr/lib/python2.6/site-packages/setuptools/dist.py", line 245, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 538, in resolve
        dist = best[req.key] = env.best_match(req, self, installer)
      File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 780, in best_match
        return self.obtain(req, installer) # try and download/install
      File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 792, in obtain
        return installer(requirement)
      File "/usr/lib/python2.6/site-packages/setuptools/dist.py", line 293, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python2.6/site-packages/setuptools/command/easy_install.py", line 466, in easy_install 
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('cffi>=1.7')

    ----------------------------------------
Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-_ihHnN/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-lm4tPa-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-_ihHnN/cryptography
```

**Comment by nichochar** [comment]
Have you found a combination of package versions that fixes the issue? We're happy to update the requirements if that fixes it for REHL. Unfortunately I don't have a REHL distro at hand to do some testing, would appreciate some help on this one.

**Comment by jschauma** [comment]
I'm afraid I have not.

But it looks like python 2.6 is not sufficient?  Or if it is, that 'pip
install' doesn't install the right things?

Unfortunately I don't have a solution as to what's needed here.

**Comment by nichochar** [comment]
Yes, we have deprecated support for python 2.6.

The minimum version is now python 2.7. We should add this to the README, thanks for the idea.

**Comment by nichochar** [comment]
We officially have dropped python 2.6 support, I am closing this ticket
