### ISSUE TITLE
startup fails

### ISSUE THREAD

**Issue by jschauma** [pinterest/snappass#75]
After running 'sudo pip install snappass' (with python 3.6), trying to run 'snappass' as per the README fails, apparently because it can't talk to any redis.  If it's required to run a redis instance, it'd be good to have the docs updated to indicate this / show how to run it or note what other things might be needed to be set up before using snappass.

```
$ snappass
Traceback (most recent call last):
  File "/home/y/lib/python3.6/site-packages/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/home/y/lib/python3.6/site-packages/redis/connection.py", line 541, in _connect
    raise err
  File "/home/y/lib/python3.6/site-packages/redis/connection.py", line 529, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/y/lib/python3.6/site-packages/redis/client.py", line 667, in execute_command
    connection.send_command(*args)
  File "/home/y/lib/python3.6/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/home/y/lib/python3.6/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/home/y/lib/python3.6/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/y/lib/python3.6/site-packages/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/home/y/lib/python3.6/site-packages/redis/connection.py", line 541, in _connect
    raise err
  File "/home/y/lib/python3.6/site-packages/redis/connection.py", line 529, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/y/lib/python3.6/site-packages/snappass/main.py", line 44, in inner
    redis_client.ping()
  File "/home/y/lib/python3.6/site-packages/redis/client.py", line 777, in ping
    return self.execute_command('PING')
  File "/home/y/lib/python3.6/site-packages/redis/client.py", line 673, in execute_command
    connection.send_command(*args)
  File "/home/y/lib/python3.6/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/home/y/lib/python3.6/site-packages/redis/connection.py", line 585, in send_packed_command self.connect()
  File "/home/y/lib/python3.6/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.

During handling of the above exception, another exception occurred:
                                                                                                    
Traceback (most recent call last):
  File "/home/y/lib/python3.6/site-packages/redis/connection.py", line 484, in connect
    sock = self._connect()
  File "/home/y/lib/python3.6/site-packages/redis/connection.py", line 541, in _connect
    raise err
  File "/home/y/lib/python3.6/site-packages/redis/connection.py", line 529, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/y/lib/python3.6/site-packages/snappass/main.py", line 44, in inner
    redis_client.ping()
  File "/home/y/lib/python3.6/site-packages/redis/client.py", line 777, in ping
    return self.execute_command('PING')
  File "/home/y/lib/python3.6/site-packages/redis/client.py", line 673, in execute_command
    connection.send_command(*args)
  File "/home/y/lib/python3.6/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/home/y/lib/python3.6/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/home/y/lib/python3.6/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/y/bin/snappass", line 11, in <module>
    sys.exit(main())
  File "/home/y/lib/python3.6/site-packages/snappass/main.py", line 47, in inner
    print('Failed to connect to redis! %s' % e.message)
AttributeError: 'ConnectionError' object has no attribute 'message'
```

**Comment by nichochar** [comment]
The redis requirement is mentioned twice in the README. In addition, if you use the `docker-compose` command, it will install both for you and set up the ports correctly. This is also in the README.

**Comment by jschauma** [comment]
Thanks for taking the time to look at this.  I'd still suggest that

1) the README could be updated to say something like "you need to run
redis" or put the step "run your redist" before the invocation of
"snappass"; and

2) that failure to talk to redis might better be bubbled up to the user
with a succinct error message (e.g. "Unable to talk to redis on
<redisurl>") instead of a big stack trace
